---
- hosts: all
  sudo: true
  user: vagrant

  tasks:
  - name: Ensure apache is installed.
    apt: pkg=apache2 state=installed

  - name: Enable the modrewrite module in Apache.
    file: src=../mods-available/rewrite.load dest=/etc/apache2/mods-enabled/rewrite.load owner=root group=root state=link
    notify: Restart Apache

  - name: Update the Apache config
    copy: src=./000-default.conf dest=/etc/apache2/sites-available/000-default.conf
    notify: Restart Apache

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted
